import type { Category, Product, StoreData } from "@/types";

function pizza(
  code: string,
  name: string,
  description: string,
  priceChica: number,
  priceGrande: number,
  sortBase: number,
): Product[] {
  return [
    {
      id: `pizza-${code}-ch`,
      name: `${name} · Chica`,
      description: `Nº ${code}. ${description}`,
      price: priceChica,
      category: "pizzas",
      available: true,
      sort_order: sortBase,
    },
    {
      id: `pizza-${code}-gr`,
      name: `${name} · Grande`,
      description: `Nº ${code}. ${description}`,
      price: priceGrande,
      category: "pizzas",
      available: true,
      sort_order: sortBase + 1,
    },
  ];
}

function calzone(
  code: string,
  name: string,
  description: string,
  priceChica: number,
  priceGrande: number,
  sortBase: number,
): Product[] {
  return [
    {
      id: `calzone-${code}-ch`,
      name: `${name} · Chica`,
      description: `Nº ${code}. ${description}`,
      price: priceChica,
      category: "calzones" as Category,
      available: true,
      sort_order: sortBase,
    },
    {
      id: `calzone-${code}-gr`,
      name: `${name} · Grande`,
      description: `Nº ${code}. ${description}`,
      price: priceGrande,
      category: "calzones",
      available: true,
      sort_order: sortBase + 1,
    },
  ];
}

function item(
  id: string,
  name: string,
  description: string,
  price: number,
  category: Category,
  sort_order: number,
): Product {
  return { id, name, description, price, category, available: true, sort_order };
}

export const DEFAULT_STORE: StoreData = {
  settings: {
    whatsapp_number: "1162345926",
    business_name: "Don Pepe",
    address: "Burgos Nº 947 Esq. M. Añeiros - Morón",
    phone: "11-6124-9867",
    tagline: "La mejor pizza a la piedra",
  },
  products: [
    // —— Promociones ——
    item(
      "promo-1",
      "2 Grandes de Muzzarella",
      "Promo 1: dos pizzas grandes de muzzarella.",
      32000,
      "promociones",
      1,
    ),
    item(
      "promo-2",
      "1 Grande de Muzza + 6 empanadas",
      "Promo 2: 1 pizza grande de muzzarella + 6 empanadas a elección.",
      30000,
      "promociones",
      2,
    ),
    item(
      "promo-3",
      "2 Gde. Muzza + 1 Gde. Fugazza con Queso",
      "Promo 3: 2 pizzas grandes de muzzarella + 1 grande de fugazza con queso.",
      50000,
      "promociones",
      3,
    ),
    item(
      "promo-4",
      "1 Gde. de Muzza + 1 Doc. Empanadas",
      "Promo 4: 1 pizza grande de muzzarella + 1 docena de empanadas a elección.",
      40000,
      "promociones",
      4,
    ),
    item(
      "promo-5",
      "1 Gde. Muzza + 1 Gde. Jamón y Morrón",
      "Promo 5: 1 pizza grande de muzzarella + 1 grande de jamón y morrón.",
      43000,
      "promociones",
      5,
    ),
    item(
      "promo-6",
      "1 Gde. de Jamón + 1 Gde. de Napolitana",
      "Promo 6: 1 pizza grande de jamón + 1 pizza grande napolitana.",
      44000,
      "promociones",
      6,
    ),

    // —— Pizzas (Chica / Grande) ——
    ...pizza(
      "00",
      "Especial Don Pepe",
      "Salsa tomate, muzzarella, tomate en cubitos, huevo rallado.",
      30000,
      33000,
      1,
    ),
    ...pizza(
      "01",
      "Canchera",
      "Salsa canchera (ajo, ají molido, perejil y orégano).",
      16500,
      17000,
      3,
    ),
    ...pizza(
      "02",
      "Muzzarella",
      "Salsa de tomate, muzzarella, aceitunas verdes.",
      15000,
      17000,
      5,
    ),
    ...pizza(
      "03",
      "Romana",
      "Salsa tomate, muzzarella, anchoas y aceitunas verdes.",
      21000,
      24000,
      7,
    ),
    ...pizza(
      "04",
      "Anchoas",
      "Salsa tomate, filet de anchoas, morrones y aceitunas.",
      21000,
      24000,
      9,
    ),
    ...pizza(
      "05",
      "Fugazza",
      "Cebolla, aceite de oliva, pimienta, orégano y aceitunas.",
      18000,
      19000,
      11,
    ),
    ...pizza(
      "06",
      "Fugazza con Queso",
      "Idem Fugazza, más muzzarella.",
      20000,
      23000,
      13,
    ),
    ...pizza(
      "07",
      "Napolitana",
      "Salsa de tomate, muzza, rodajas de tomate, aceite de oliva, ajo y aceitunas.",
      22000,
      25000,
      15,
    ),
    ...pizza(
      "08",
      "Napolitana Especial",
      "Idem Napolitana, más jamón.",
      26000,
      29000,
      17,
    ),
    ...pizza(
      "09",
      "Jamón",
      "Salsa de tomate, muzza, jamón, aceite de oliva, aceitunas.",
      22000,
      25000,
      19,
    ),
    ...pizza(
      "10",
      "Especial de Jamón",
      "Idem Jamón y Morrón.",
      27000,
      30000,
      21,
    ),
    ...pizza(
      "11",
      "Jamón y Huevo",
      "Salsa de tomate, muzza, jamón, huevo, orégano y aceitunas.",
      25000,
      28000,
      23,
    ),
    ...pizza(
      "12",
      "Doble Muzzarella",
      "Salsa de tomate, doble porc. muzzarella, orégano y aceitunas.",
      21000,
      24000,
      25,
    ),
    ...pizza(
      "13",
      "Jamaica",
      "Salsa tomate, muzzarella, jamón, rodajas ananá, morrón y aceitunas.",
      29000,
      33000,
      27,
    ),
    ...pizza(
      "14",
      "Calabresa",
      "Salsa de tomate, muzzarella, longaniza.",
      23000,
      25000,
      29,
    ),
    ...pizza(
      "15",
      "Calabresa Especial",
      "Salsa de tomate, muzzarella, longaniza y morrones.",
      26000,
      29000,
      31,
    ),
    ...pizza(
      "16",
      "Especial Completa",
      "Salsa de tomate, muzzarella, rod. tomate, jamón y morrón.",
      26000,
      29000,
      33,
    ),
    ...pizza(
      "17",
      "Roquefort",
      "Salsa tomate, muzzarella y roquefort.",
      23000,
      26000,
      35,
    ),
    ...pizza(
      "18",
      "Palmitos",
      "Salsa de tomate, muzza, jamón, huevo duro, palmitos y salsa golf.",
      30000,
      34000,
      37,
    ),
    ...pizza(
      "19",
      "Fugazzeta común",
      "Muzzarella, cebolla, aceite de oliva y orégano (relleno).",
      24000,
      27000,
      39,
    ),
    ...pizza(
      "20",
      "Fugazzeta Especial",
      "Idem fugazzeta común + jamón (relleno).",
      27000,
      31000,
      41,
    ),
    ...pizza(
      "25",
      "Pizza de Verduras",
      "Salsa, muzzarella, verdura con salsa blanca y morrones y aceitunas verdes.",
      22000,
      25000,
      43,
    ),
    ...pizza(
      "26",
      "Provolone",
      "Salsa de tomate, jamón, muzzarella, provolone y aceitunas negras.",
      25000,
      28000,
      45,
    ),
    ...pizza(
      "27",
      "Rúcula y Jamón Crudo",
      "Salsa, muzzarella, rúcula, jamón crudo y aceitunas.",
      24000,
      29000,
      47,
    ),
    ...pizza(
      "28",
      "Española",
      "Salsa de tomate, muzzarella, huevo duro rallado, aceitunas verdes.",
      23000,
      26000,
      49,
    ),
    ...pizza(
      "29",
      "Primavera Especial",
      "Salsa, muzzarella, rodajas de tomate al natural, jamón, huevo rallado y aceitunas verdes.",
      25000,
      28000,
      51,
    ),
    ...pizza(
      "30",
      "4 quesos",
      "Salsa de tomate, muzzarella, queso azul, provolone, aceitunas negras.",
      23000,
      26000,
      53,
    ),

    // —— Empanadas ——
    item(
      "empa-docena",
      "1 Docena de empanadas",
      "12 empanadas a elección.",
      24000,
      "empanadas",
      1,
    ),
    item(
      "empa-media-docena",
      "½ Docena de empanadas",
      "6 empanadas a elección.",
      13000,
      "empanadas",
      2,
    ),
    item(
      "empa-carne-cuchillo",
      "Carne cortada a cuchillo",
      "Empanada de carne cortada a cuchillo. Precio por unidad.",
      2500,
      "empanadas",
      3,
    ),
    item(
      "empa-carne-roticera",
      "Carne Rotisera",
      "Empanada de carne rotisera. Precio por unidad.",
      2500,
      "empanadas",
      4,
    ),
    item(
      "empa-pollo",
      "Pollo",
      "Empanada de pollo. Precio por unidad.",
      2500,
      "empanadas",
      5,
    ),
    item(
      "empa-jyq",
      "Jamón y Queso",
      "Empanada de jamón y queso. Precio por unidad.",
      2500,
      "empanadas",
      6,
    ),
    item(
      "empa-jtyq",
      "Jamón, Tomate y Queso",
      "Empanada de jamón, tomate y queso. Precio por unidad.",
      2500,
      "empanadas",
      7,
    ),
    item(
      "empa-roque-jamon",
      "Roquefort con Jamón",
      "Empanada de roquefort con jamón. Precio por unidad.",
      2500,
      "empanadas",
      8,
    ),
    item(
      "empa-humita",
      "Humita",
      "Empanada de humita. Precio por unidad.",
      2500,
      "empanadas",
      9,
    ),
    item(
      "empa-cebolla-queso",
      "Cebolla y Queso",
      "Empanada de cebolla y queso. Precio por unidad.",
      2500,
      "empanadas",
      10,
    ),
    item(
      "empa-verdura",
      "Verdura",
      "Empanada de verdura. Precio por unidad.",
      2500,
      "empanadas",
      11,
    ),

    // —— Calzones ——
    ...calzone(
      "21",
      "Calzone Tradicional",
      "Salsa de tomate, muzza, aceite de oliva, ajo y jamón, rodajas de tomate natural.",
      29000,
      31000,
      1,
    ),
    ...calzone(
      "22",
      "Calzone Roquefort",
      "Idem calzone tradicional + roquefort.",
      29000,
      33000,
      3,
    ),
    ...calzone(
      "23",
      "Calzone Calabresa",
      "Muzzarella, rodajas de tomate, longaniza, jamón.",
      29000,
      33000,
      5,
    ),
    ...calzone(
      "24",
      "Calzone de Verduras",
      "Base de jamón, muzzarella, verdura, salsa blanca y morrones. Ajo, orégano y aceitunas.",
      23000,
      33000,
      7,
    ),

    // —— Fainá ——
    item("faina-cu", "Fainá", "Fainá clásica. Precio por unidad.", 2500, "faina", 1),
    item(
      "faina-roque",
      "Fainá c/ Roquefort",
      "Fainá con roquefort. Precio por unidad.",
      3000,
      "faina",
      2,
    ),
    item(
      "faina-jyq",
      "Fainá c/ Jamón y Queso",
      "Fainá con jamón y queso. Precio por unidad.",
      3000,
      "faina",
      3,
    ),
    item(
      "faina-cyq",
      "Fainá c/ Cebolla y Queso",
      "Fainá con cebolla y queso. Precio por unidad.",
      3000,
      "faina",
      4,
    ),

    // —— Bebidas ——
    item(
      "bebida-gaseosa",
      "Gaseosa",
      "Gaseosa. También se puede sumar a las promociones (+$3.000).",
      3000,
      "bebidas",
      1,
    ),
  ],
};
